// PWA + SSG output smoke.
//
// Scope: assert each SEO route renders + each is server-rendered
// (HTML body has content before JS runs), and the service worker
// + manifest are present at expected paths. Full offline-behavior
// testing (load page → go offline → reload → still works) is
// over-scope; Playwright's offline emulation requires service
// worker registration completion which is timing-fragile.

import { test, expect } from '@playwright/test';

// Routes generated by vite-react-ssg per src/routes.tsx — each
// emits an HTML file (e.g. dist/json-viewer.html) at build time.
const SSG_ROUTES = [
  '/',
  '/json-viewer',
  '/large-json-viewer',
  '/ndjson-viewer',
  '/json-repair',
];

for (const route of SSG_ROUTES) {
  test(`SSG: ${route} renders with body content pre-hydration`, async ({
    page,
  }) => {
    // Disable JS to assert the HTML body has real content from SSG,
    // not just the React placeholder div. Without SSG, the body
    // would be near-empty until the JS bundle executes.
    await page.context().route('**/*.{js,mjs}', (route) => route.abort());
    const response = await page.goto(route);
    expect(response?.status()).toBe(200);
    // The body should contain SOME content — at minimum the
    // brand / heading + nav. The exact copy depends on the route,
    // so check for the presence of any text content beyond the
    // initial Vite shell.
    const bodyText = await page.locator('body').textContent();
    expect(bodyText?.trim().length ?? 0).toBeGreaterThan(50);
  });
}

test('PWA: sw.js + manifest are served at expected paths', async ({
  page,
}) => {
  // sw.js is generated by vite-plugin-pwa. manifest.webmanifest
  // by the PWA plugin's manifest config.
  const swResp = await page.goto('/sw.js');
  expect(swResp?.status()).toBe(200);
  // SW source should include workbox boilerplate (precache etc.).
  const swText = await page.content();
  expect(swText.toLowerCase()).toContain('workbox');

  const manifestResp = await page.goto('/manifest.webmanifest');
  expect(manifestResp?.status()).toBe(200);
});
